### PR TITLE
Add 'On HTML element click' action source for HTML card (static and v…

### PR DESCRIPTION
**Pull request by pgrisu**
…alue) widgets

This is useful especially to create static HTML widgets for dashboard states navigation by clicking text or icons

### CODE REVIEW

**Comment by ikulikov** [comment]
@pgrisu Thx for your contribution!

**Comment by advset** [comment]
Thank you very much for your contribution, but when I tried it, it doesn't work. Unlike action buttons which will direct us to another dashboard/state, the "on html element click" don't get me anywhere (like nothing happened). Is there any other who experiencing similar issue?

**Comment by pgrisu** [comment]
Hello advset, I can confirm that the 'on element click' is working fine.
Please check that you properly placed HTML IDs on HTML elements where you want the 'action on click' and that configura the widget actions using the HTML IDs as action names.

Below a widget example (it's a sort of dashboard state toolbar) where I used the 'on HTML click' actions to navigate on others dashboard states

[new_html_value_card.zip](https://github.com/thingsboard/thingsboard/files/3455398/new_html_value_card.zip)

**Comment by nmahale10** [comment]
> Hello advset, I can confirm that the 'on element click' is working fine.
> Please check that you properly placed HTML IDs on HTML elements where you want the 'action on click' and that configura the widget actions using the HTML IDs as action names.
> 
> Below a widget example (it's a sort of dashboard state toolbar) where I used the 'on HTML click' actions to navigate on others dashboard states
> 
> [new_html_value_card.zip](https://github.com/thingsboard/thingsboard/files/3455398/new_html_value_card.zip)

I am not able to find JS in the widget. Can you please help. I want to create similar widget.

**Pull request merged**
