### PR TITLE
[3.4.2] MQTT transport: Make log shorter on IOException

### PR DESCRIPTION
**Pull request by smatvienko-tb**
## MQTT Transport: Make log shorter on IOException

Issue: https://github.com/thingsboard/thingsboard/issues/7523
PE PR: https://github.com/thingsboard/thingsboard-pe/pull/1222

IOException is not an ordinary exception INFO level. Others will be fired under the error log level.

Device name added for already connected devices, but it needs to be validated by the reviewer @ashvayka : exposing the device name on the transport log is possibly unwanted from a security perspective.

Also, is possible to implement such an improvement in other `exceptionCaught` implementations across the ThingsBoard.

```
2022-07-16 22:42:21,666 [nioEventLoopGroup-3-12] INFO  o.t.s.t.mqtt.MqttTransportHandler - [6beda097-df65-4545-9c23-442c5f91864e][DW00873258] IOException: Connection reset by peer
```

image
**UPD: deviceId will be logged between sessionId and deviceName**

Before this, we had an error log with the same stack trace all the time. It just wastes computing resources and make log unreadable. Especially on massive reconnect events.

## General checklist

- [x] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [x] PR name contains fix version. For example, "[3.3.4] Hotfix of some UI component" or "[3.4] New Super Feature".
- [x] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [x] Description contains human-readable scope of changes.
- [x] Description contains brief notes about what needs to be added to the documentation.
- [x] No merge conflicts, commented blocks of code, code formatting issues.
- [x] Changes are backward compatible or upgrade script is provided.
- [x] Similar PR is opened for PE version to simplify merge. Required for internal contributors only.
  
## Front-End feature checklist

- [x] Screenshots with affected component(s) are added. The best option is to provide 2 screens: before and after changes;
- [x] If you change the widget or other API, ensure it is backward-compatible or upgrade script is present.
- [x] Ensure new API is documented [here](https://github.com/thingsboard/thingsboard-ui-help)

## Back-End feature checklist

- [x] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [x] If new dependency was added: the dependency tree is checked for conflicts.
- [x] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [x] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.

### CODE REVIEW

**Comment by smatvienko-tb** [comment]
reopened from auto-closed PR https://github.com/thingsboard/thingsboard/pull/6956

**Comment by ashvayka** [comment]
The screenshot is misleading because the log level is INFO on the screen but DEBUG in the code. So, the correct fix would be:

```
        if (cause instanceof IOException) {
            if (log.isDebugEnabled()) {
                log.debug("[{}][{}] IOException: {}", sessionId,
                        Optional.ofNullable(this.deviceSessionCtx.getDeviceInfo()).map(TransportDeviceInfo::getDeviceName).orElse(""), cause);
            } else if (log.isInfoEnabled()){
                log.info("[{}][{}] IOException: {}", sessionId,
                        Optional.ofNullable(this.deviceSessionCtx.getDeviceInfo()).map(TransportDeviceInfo::getDeviceName).orElse(""),
                        cause.getMessage());
            }
        } else {
            log.error("[{}] Unexpected Exception", sessionId, cause);
        }
```

**Comment by ashvayka** [comment]
BTW, are you sure that the 'this.deviceSessionCtx' is not null?

**Comment by smatvienko-tb** [comment]
> BTW, are you sure that the 'this.deviceSessionCtx' is not null?

It is always non-null because it's final and fills in the constructor. We call it safely from many places in the same class.
```
this.deviceSessionCtx = new DeviceSessionCtx(sessionId, mqttQoSMap, context);
```

**Comment by smatvienko-tb** [comment]
> The screenshot is misleading because the log level is INFO on the screen but DEBUG in the code. So, the correct fix would be:
> 
> ```
>         if (cause instanceof IOException) {
>             if (log.isDebugEnabled()) {
>                 log.debug("[{}][{}] IOException: {}", sessionId,
>                         Optional.ofNullable(this.deviceSessionCtx.getDeviceInfo()).map(TransportDeviceInfo::getDeviceName).orElse(""), cause);
>             } else if (log.isInfoEnabled()){
>                 log.info("[{}][{}] IOException: {}", sessionId,
>                         Optional.ofNullable(this.deviceSessionCtx.getDeviceInfo()).map(TransportDeviceInfo::getDeviceName).orElse(""),
>                         cause.getMessage());
>             }
>         } else {
>             log.error("[{}] Unexpected Exception", sessionId, cause);
>         }
> ```

improved regarding your suggestions

**Pull request merged**
