### PR TITLE
Feature/aws kinesis extension

### PR DESCRIPTION
**Pull request by michalolsze**

### CODE REVIEW

**Comment by michalolsze** [comment]
Of course! I will create a new PR against develop/1.5

W dniu pt., 27.04.2018 o 18:47 Andrew Shvayka <notifications@github.com>
napisał(a):

**Comment by ashvayka** [comment]
Please note that now you need to implement TbNode. The easiest way to understand how it works is to review other TbNode implementations. Also, feel free to submit a PR with a skeleton or send me an email with questions: ashvayka@thingsboard.io. Please use topic "Kinesis rule node" or similar.

**Comment by ashvayka** [comment]
@mp-loki please help to review this PR.

**Comment by michalolsze** [comment]
@ashvayka I tried to test a bit the new rule engine and I think it is to early to introduce my changes there. I mean it seems don't work correctly so far, so I cannot investigate and debug it reasonably. I got the idea, but I cannot test with current implementation (with real rule chain created via GUI and telemetry I am sending).

**Comment by ashvayka** [comment]
Hi @michalolsze . We have moved all code to develop/2.0. We will merge your code to master branch, but there is no release planned for 1.4 so far. We hope you can try to introduce your changes to TB/2.0 one more time within a week. This week we will make the official release candidate. I believe issues you were facing are fixed now. Feel free to report issue on my email listed above. We are interested to make this code part of TB 2.0

**Comment by ashvayka** [comment]
Closing due to inactivity and since rule engine is completely refactored now to rule nodes instead of plugins.

**Pull request closed without merging**
