### PR TITLE
Added 'Disable scroll zooming' setting for all map types

### PR DESCRIPTION
**Pull request by Terny22**

### CODE REVIEW

**Comment by ikulikov** [comment]
@Terny22 Please resolve merge conflicts!

**Comment by Terny22** [comment]
Resolved.

**Comment by ikulikov** [comment]
@Terny22 Please resolve merge conflicts!

**Comment by Terny22** [comment]
@ikulikov Please, don't merge for now... need to add some changes to the "trip-animation" widget as well.

**Comment by Terny22** [comment]
@ikulikov Ready to merge!

**Pull request merged**
