### PR TITLE
Feature - Thingsboard Helm Chart

### LINKED ISSUE #3741: [Feature Request] Create a helm chart for deploying on kubernetes
Currently for deploying on kubernetes is running shell scripts which create the kubernetes resources. Having a helm chart for doing that would allow for easier configuration, upgrade and deletion of thingsboards resources.

Is the creation of an helm chart something that could be useful for other people ?

### PR DESCRIPTION
**Pull request by ArieLevs**
Adding the Thingsboard helm chart,
Chart was tested successfully (using `docker-desktop` on macOS without changing anything in the values.yaml file).
In addition tested successfully on on-prem k8s cluster (v1.21.0).

- [x] cassandra hybrid mode **fixed**  
  *  currently Cassandra **cannot** be set to `true`, the `thingsboard-db-setup-job.yaml` gets stuck, I suspect its due to the fact that Cassandra chart is setting default username/password, but the `start-tb-node.sh` script does not take any of these arguments. if anyone can point me to the source code of `start-tb-node.sh` in `thingsboard/tb-node` image would be grate.

additional feature contributions would be welcome (I'll add HPA/Keda scale in the future)

fixes #3741

### CODE REVIEW

**Comment by vvlladd28** [comment]
Hi @ArieLevs,
Point for source code `start-tb-node.sh`: https://github.com/thingsboard/thingsboard/blob/master/msa/tb-node/docker/start-tb-node.sh

**Comment by ArieLevs** [comment]
Hi @vvlladd28,

Thanks for the guidance, I was able to track the [CASSANDRA_USE_CREDENTIALS](https://github.com/thingsboard/thingsboard/blob/b14e845e4d9d1d4f315bdf54b612875fbda94e8a/application/src/main/resources/thingsboard.yml#L184) parameter (which also explained in the [official docs](https://thingsboard.io/docs/user-guide/install/config/) that I managed to miss :sweat_smile:)

above cassandra/hybrid setup comment updated.

please review.

**Comment by ashvayka** [comment]
Hi @ArieLevs , please move this PR to the https://github.com/thingsboard/thingsboard-ce-k8s project. You can find many useful scripts there.

**Comment by ArieLevs** [comment]
PR moved: https://github.com/thingsboard/thingsboard-ce-k8s/pull/28

**Pull request closed without merging**
