### PR TITLE
CORS

### PR DESCRIPTION
**Pull request by yuyihan666**
Support for cross-domain sharing configuration

### CODE REVIEW

**Comment by ashvayka** [comment]
@yuyihan666 please sign the CLA using @CLAassistant and we will merge

**Comment by ashvayka** [comment]
@yuyihan666 please associate other email address that you have used in original commit with your github account to match the CLAassstant check. Otherwise I can't merge the code with unknown author.

**Comment by ashvayka** [comment]
in order to fix license header you can just execute
"mvn license:format"

**Comment by yuyihan666** [comment]
@ashvayka thank you very much

**Pull request merged**
