### PR TITLE
Allow to configure kafkajs `connectionTimeout` property

### PR DESCRIPTION
**Pull request by AndreMaz**
## Pull Request description

Related issue: https://github.com/thingsboard/thingsboard/issues/7986#issuecomment-1403382688

This PR allows to configure kafkajs `connectionTimeout` property that defaults to 1000ms (link https://github.com/tulios/kafkajs/blob/dcee6971c4a739ebb02d9279f68155e3945c50f7/src/index.js#L56)  via `TB_KAFKA_CONNECTION_TIMEOUT_MS` env var.

Note: To create this PR I tried to mimic the logic that already exists for the `requestTimeout` property.

PS: I'm not sure if I have to add the new var in here (and other `yaml` files):
https://github.com/thingsboard/thingsboard/blob/c7babf20850007b611256dbfee9ab47863a2033c/transport/http/src/main/resources/tb-http-transport.yml#L154-L158

Required changes in docs: 
Add a new entry in the config docs (link https://thingsboard.io/docs/user-guide/install/config/#queue-parameters) regarding the TB_KAFKA_CONNECTION_TIMEOUT_MS env var.

Provide written explanation in the PR description if you have failed to add tests:
Sorry but I did find any place where this is tested. If unit test is required for this change please provide a pointer  where I can do it.

## General checklist

- [x] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [ ] PR name contains fix version. For example, "[3.3.4] Hotfix of some UI component" or "[3.4] New Super Feature".
- [ ] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [x] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [x] Description contains human-readable scope of changes.
- [x] Description contains brief notes about what needs to be added to the documentation.
- [x] No merge conflicts, commented blocks of code, code formatting issues.
- [x] Changes are backward compatible or upgrade script is provided.
- [ ] Similar PR is opened for PE version to simplify merge. Required for internal contributors only.
  
## Back-End feature checklist

- [ ] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [ ] If new dependency was added: the dependency tree is checked for conflicts.
- [ ] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [ ] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.

### CODE REVIEW

**Comment by AndreMaz** [comment]
@volodymyr-babak sorry for tagging you but can you please take a look at this?

I'm facing a connection timeout issues again
> 2023-03-10 18:43:35,878 [kafkajs] ERROR: Connection timeout: {"timestamp":"2023-03-10T18:43:35.878Z","logger":"kafkajs","broker":"","clientId":"kafkajs"}

**Comment by ashvayka** [comment]
@vvlladd28  and @volodymyr-babak, this PR looks valid. Please approve separately.

**Review by vvlladd28 — APPROVED** [review]

**Comment by volodymyr-babak** [comment]
@AndreMaz 

Thank you for submitting this Pull Request. It appears that the implementation of the code is correct, but it has not been verified in the runtime environment. Could you please confirm that you have tested this on your own environment and have verified that this fixes the connection timeout error? It would be helpful to receive confirmation before we proceed with merging this change.

**Review by volodymyr-babak — APPROVED** [review]
LGTM

**Pull request merged**
