### PR TITLE
kafka: added TB_KAFKA_COMPRESSION_TYPE for producer: none (default), …

### PR DESCRIPTION
**Pull request by smatvienko-tb**
…gzip.

### CODE REVIEW

**Comment by smatvienko-tb** [comment]
https://kafka.apache.org/documentation/#producerconfigs_compression.type

**Comment by smatvienko-tb** [comment]
Here an example how compressed Kafka logs look like:
image

**Comment by ashvayka** [comment]
Is this battle-tested for our setup? :-)

**Comment by smatvienko-tb** [comment]
Just applied to the stage. Its working fine now. Anyway, it is just a
standard Kafka option. Default compression is none. Gzip is optional.

**Pull request merged**
