### PR TITLE
Optimize rule nodes ids search in the upgrade process

### PR DESCRIPTION
**Pull request by ShvaykaD**
## Pull Request description

This PR introduces a new index for the rule_node table to optimize query performance, particularly for those with LIMIT clauses, and removes an older, less efficient index. 

- Created a composite index on type, id and configuration_version for faster query execution and efficient index-only scans.
- Dropped single column index on type and composite index on type and configuration_version to enhance database efficiency.

**Tests:**

```
thingsboard_test_rule_node_ids_search_query=# DROP INDEX IF EXISTS idx_rule_node_type_configuration_version_id;
DROP INDEX
thingsboard_test_rule_node_ids_search_query=# CREATE INDEX IF NOT EXISTS idx_rule_node_type_id_configuration_version ON rule_node(type, id, configuration_version);
CREATE INDEX
thingsboard_test_rule_node_ids_search_query=# VACUUM FULL rule_node;
VACUUM
thingsboard_test_rule_node_ids_search_query=# EXPLAIN ANALYZE (SELECT r.id as id FROM rule_node r WHERE r.type = 'org.thingsboard.rule.engine.telemetry.TbMsgAttributesNode' AND r.configuration_version < 2 ORDER BY r.id ASC nulls last limit 1024);
                                                                                   QUERY PLAN                                                                                    
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.56..1284.57 rows=1024 width=16) (actual time=57.175..57.176 rows=0 loops=1)
   ->  Index Only Scan using idx_rule_node_type_id_configuration_version on rule_node r  (cost=0.56..407739.12 rows=325172 width=16) (actual time=57.172..57.172 rows=0 loops=1)
         Index Cond: ((type = 'org.thingsboard.rule.engine.telemetry.TbMsgAttributesNode'::text) AND (configuration_version < 2))
         Heap Fetches: 0
 Planning Time: 0.672 ms
 Execution Time: 57.227 ms
(6 rows)
```

```
thingsboard_test_rule_node_ids_search_query=# EXPLAIN ANALYZE (SELECT r.id as id FROM rule_node r WHERE r.type = 'org.thingsboard.rule.engine.telemetry.TbMsgAttributesNode' ORDER BY r.id ASC nulls last limit 1024);
                                                                                    QUERY PLAN                                                                                    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.56..1110.73 rows=1024 width=16) (actual time=0.179..8.118 rows=1024 loops=1)
   ->  Index Only Scan using idx_rule_node_type_id_configuration_version on rule_node r  (cost=0.56..407415.28 rows=375791 width=16) (actual time=0.176..7.812 rows=1024 loops=1)
         Index Cond: (type = 'org.thingsboard.rule.engine.telemetry.TbMsgAttributesNode'::text)
         Heap Fetches: 1024
 Planning Time: 0.230 ms
 Execution Time: 8.340 ms
(6 rows)
```

```
thingsboard_test_rule_node_ids_search_query=# EXPLAIN ANALYZE(SELECT r.id as id FROM rule_node r WHERE r.type = 'org.thingsboard.rule.engine.telemetry.TbMsgAttributesNode' AND r.configuration_version < 3 and r.id > '00b86ac0-ebb4-11ed-9f6b-dfd3cdc481bf' ORDER BY r.id ASC nulls last limit 1024);
                                                                                        QUERY PLAN                                                                                        
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.56..1121.07 rows=1024 width=16) (actual time=0.095..5.173 rows=1024 loops=1)
   ->  Index Only Scan using idx_rule_node_type_id_configuration_version on rule_node r  (cost=0.56..409155.85 rows=373912 width=16) (actual time=0.092..4.959 rows=1024 loops=1)
         Index Cond: ((type = 'org.thingsboard.rule.engine.telemetry.TbMsgAttributesNode'::text) AND (id > '00b86ac0-ebb4-11ed-9f6b-dfd3cdc481bf'::uuid) AND (configuration_version < 3))
         Heap Fetches: 1024
 Planning Time: 0.445 ms
 Execution Time: 5.342 ms
(6 rows)
```

```
thingsboard_test_rule_node_ids_search_query=# EXPLAIN ANALYZE (SELECT r.id as id FROM rule_node r WHERE r.type = 'org.thingsboard.rule.engine.telemetry.TbMsgAttributesNode' AND r.configuration_version < 2 ORDER BY r.id DESC nulls first limit 1024);
                                                                                        QUERY PLAN                                                                                        
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.56..1284.57 rows=1024 width=16) (actual time=30.996..30.997 rows=0 loops=1)
   ->  Index Only Scan Backward using idx_rule_node_type_id_configuration_version on rule_node r  (cost=0.56..407739.12 rows=325172 width=16) (actual time=30.994..30.994 rows=0 loops=1)
         Index Cond: ((type = 'org.thingsboard.rule.engine.telemetry.TbMsgAttributesNode'::text) AND (configuration_version < 2))
         Heap Fetches: 0
 Planning Time: 0.245 ms
 Execution Time: 31.036 ms
(6 rows)
```

Verified that we use ID ACS NULLS LAST:

```
2024-01-03 10:33:09,176 [main] INFO  o.t.s.s.i.u.DefaultDataUpdateService - Starting rule nodes upgrade ...
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
Hibernate: select rulenodeen0_.id as col_0_0_ from rule_node rulenodeen0_ where rulenodeen0_.type=? and rulenodeen0_.configuration_version<? order by rulenodeen0_.id asc nulls last limit ?
```

## PE PR

A separate PR for the PE was deemed unnecessary as the changes introduced have no conflicts with the PE version and can be merged without additional modifications or conflict resolution.

## General checklist

- [x] You have reviewed the guidelines [document](https://docs.google.com/document/d/1wqcOafLx5hth8SAg4dqV_LV3un3m5WYR8RdTJ4MbbUM/edit?usp=sharing).
- [x] [Labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-labels) that classify your pull request have been added.
- [x] The [milestone](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) is specified and corresponds to fix version.  
- [x] Description references specific [issue](https://github.com/thingsboard/thingsboard/issues).
- [x] Description contains human-readable scope of changes.
- [x] Description contains brief notes about what needs to be added to the documentation.
- [x] No merge conflicts, commented blocks of code, code formatting issues.
- [x] Changes are backward compatible or upgrade script is provided.
- [x] Similar PR is opened for PE version to simplify merge. Crosslinks between PRs added. Required for internal contributors only.
  
## Front-End feature checklist

- [x] Screenshots with affected component(s) are added. The best option is to provide 2 screens: before and after changes;
- [x] If you change the widget or other API, ensure it is backward-compatible or upgrade script is present.
- [x] Ensure new API is documented [here](https://github.com/thingsboard/thingsboard-ui-help)

## Back-End feature checklist

- [x] Added corresponding unit and/or integration test(s). Provide written explanation in the PR description if you have failed to add tests.
- [x] If new dependency was added: the dependency tree is checked for conflicts.
- [x] If new service was added: the service is marked with corresponding @TbCoreComponent, @TbRuleEngineComponent, @TbTransportComponent, etc.
- [x] If new REST API was added: the RestClient.java was updated, issue for [Python REST client](https://github.com/thingsboard/thingsboard-python-rest-client) is created.
- [x] If new yml property was added: make sure a description is added (above or near the property).

### CODE REVIEW

**Review by smatvienko-tb — CHANGES_REQUESTED** [review]
The RuleNode table update rate is relatively low. 
So you can afford to create any index to improve your query.

As far as I see the problem described is not relevant to the query by itself.

Your query has a page link. It means that SORT by ID will be added to the query and after that, the LIMIT will take place.

Bitmap Index scan is working just fine with index 
```
CREATE INDEX IF NOT EXISTS idx_rule_node_type_configuration_version ON rule_node(type, configuration_version);
```
However, it is not enough information to sort the output by ID using the index. That is why the heap scan took place.
image

image

What can we do?
1. include the `id` into the index (will use index only bitmap scan) - kind of cover index. 
- Postgres will sort it in the memory and apply the limit
```
CREATE INDEX idx_rule_node_type_configuration_version
    ON public.rule_node USING btree
    (type, configuration_version)
    INCLUDE(id);
```
2. add `id` as a regular field to the index `rule_node(type, id, configuration_version)`
- Postgres will fetch already sorted data from index only by type**=**, id**>**, configuration_version**<**

Please, try just improve the index and avoid adding complexity to already existing scripts.

**One more**:
You can also remove the index `idx_rule_node_type`  in favour much wider  `idx_rule_node_type_configuration_version`

```
CREATE INDEX IF NOT EXISTS idx_rule_node_type ON rule_node(type); -- remove this
```

**Comment by ShvaykaD** [comment]
> The RuleNode table update rate is relatively low. So you can afford to create any index to improve your query.
> 
> As far as I see the problem described is not relevant to the query by itself.
> 
> Your query has a page link. It means that SORT by ID will be added to the query and after that, the LIMIT will take place.
> 
> Bitmap Index scan is working just fine with index
> 
> ```
> CREATE INDEX IF NOT EXISTS idx_rule_node_type_configuration_version ON rule_node(type, configuration_version);
> ```
> 
> However, it is not enough information to sort the output by ID using the index. That is why the heap scan took place. image
> 
> image
> 
> What can we do?
> 
> 1. include the `id` into the index (will use index only bitmap scan) - kind of cover index.
> 
> * Postgres will sort it in the memory and apply the limit
> 
> ```
> CREATE INDEX idx_rule_node_type_configuration_version
>     ON public.rule_node USING btree
>     (type, configuration_version)
>     INCLUDE(id);
> ```
> 
> 2. add `id` as a regular field to the index `rule_node(type, id, configuration_version)`
> 
> * Postgres will fetch already sorted data from index only by type**=**, id**>**, configuration_version**<**
> 
> Please, try just improve the index and avoid adding complexity to already existing scripts.
> 
> **One more**: You can also remove the index `idx_rule_node_type` in favour much wider `idx_rule_node_type_configuration_version`
> 
> ```
> CREATE INDEX IF NOT EXISTS idx_rule_node_type ON rule_node(type); -- remove this
> ```

1. I have tested both approaches:

- covering index (include id)
- composite index (id, type, configuration_version) 

The result for the first one was still slow and the planner didn't use a covering index:


```
-------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.43..1844.78 rows=1024 width=16) (actual time=169888.872..169888.872 rows=0 loops=1)
   ->  Index Scan using rule_node_pkey on rule_node r  (cost=0.43..581706.53 rows=322968 width=16) (actual time=169888.870..169888.870 rows=0 loops=1)
         Filter: ((configuration_version < 2) AND ((type)::text = 'org.thingsboard.rule.engine.telemetry.TbMsgAttributesNode'::text))
         Rows Removed by Filter: 2795503
 Planning Time: 0.165 ms
 Execution Time: 169888.900 ms
(6 rows)
```

2. I didn't remove the index for type: idx_rule_node_type. Since we still have queries that use it.

3. PR description updated.

**Comment by smatvienko-tb** [comment]
Hey!

The order of the fields in the index matters as we are using a B-Tree.

My suggestion was `rule_node(type, id, configuration_version)`
The `type` is in the first place. And it replaces the `rule_node(type)`

Another variation possible is `rule_node(type, configuration_version, id)`

Having the `id` in the first place makes no sense for searching by `type`.

If you are testing with 2M rows, the statistics should be up to date. VACUUM ANALYSE or VACUUL FULL is mandatory.
The distribution of the desired fields should be as fair as possible.

Ensure that the sort by ID ACS NULLS LAST. or DESC NULLS FIRST. The order in the index and in the query should maintain the same NULLS order



> > The RuleNode table update rate is relatively low. So you can afford to create any index to improve your query.
> > As far as I see the problem described is not relevant to the query by itself.
> > Your query has a page link. It means that SORT by ID will be added to the query and after that, the LIMIT will take place.
> > Bitmap Index scan is working just fine with index
> > ```
> > CREATE INDEX IF NOT EXISTS idx_rule_node_type_configuration_version ON rule_node(type, configuration_version);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, it is not enough information to sort the output by ID using the index. That is why the heap scan took place. image
> > image
> > What can we do?
> > 
> > 1. include the `id` into the index (will use index only bitmap scan) - kind of cover index.
> > 
> > 
> > * Postgres will sort it in the memory and apply the limit
> > 
> > ```
> > CREATE INDEX idx_rule_node_type_configuration_version
> >     ON public.rule_node USING btree
> >     (type, configuration_version)
> >     INCLUDE(id);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. add `id` as a regular field to the index `rule_node(type, id, configuration_version)`
> > 
> > 
> > * Postgres will fetch already sorted data from index only by type**=**, id**>**, configuration_version**<**
> > 
> > Please, try just improve the index and avoid adding complexity to already existing scripts.
> > **One more**: You can also remove the index `idx_rule_node_type` in favour much wider `idx_rule_node_type_configuration_version`
> > ```
> > CREATE INDEX IF NOT EXISTS idx_rule_node_type ON rule_node(type); -- remove this
> > ```
> 
> Hi @smatvienko-tb,
> 
>     1. I have tested both approaches:
> 
> 
>     * covering index (include id)
> 
>     * composite index (id, type, configuration_version)
> 
> 
> The result for the first one was still slow and the planner didn't use a covering index:
> 
> ```
> -------------------------------------------------------------------------------------------------------------------------------------------------------
>  Limit  (cost=0.43..1844.78 rows=1024 width=16) (actual time=169888.872..169888.872 rows=0 loops=1)
>    ->  Index Scan using rule_node_pkey on rule_node r  (cost=0.43..581706.53 rows=322968 width=16) (actual time=169888.870..169888.870 rows=0 loops=1)
>          Filter: ((configuration_version < 2) AND ((type)::text = 'org.thingsboard.rule.engine.telemetry.TbMsgAttributesNode'::text))
>          Rows Removed by Filter: 2795503
>  Planning Time: 0.165 ms
>  Execution Time: 169888.900 ms
> (6 rows)
> ```
> 
>     2. I didn't remove the index for type: idx_rule_node_type. Since we still have queries that use it.
> 
>     3. PR description updated.

**Review by smatvienko-tb — APPROVED** [review]
Hi! Great job. Now, it looks good to me.

**Pull request merged**
