### PR TITLE
Fixed the issue when the user is not authorized and the publicId i…

### PR DESCRIPTION
**Pull request by GinMu**
…s not empty

### CODE REVIEW

**Comment by GinMu** [comment]
when the publicId is not empty and the user is not authenticated, click the sign-in button on the dialog lead to loop request 'api/auth/login/public' api.
image

**Comment by ashvayka** [comment]
Hi @GinMu . FYI: we have used your fix and going to improve it to cover all the cases. I will update this thread with latest changes in a minute.

**Comment by ashvayka** [comment]
@GinMu please take a look at this changes: https://github.com/thingsboard/thingsboard/commit/e87f1326f552ff802ddd73ddd72ac46293e9c96a

**Comment by GinMu** [comment]
Ok, thx

**Pull request merged**
