### PR TITLE
mysql integration

### PR DESCRIPTION
**Pull request by wind86**

### CODE REVIEW

**Comment by ashvayka** [comment]
Hi! I assume the tests are working because they are on HSQLDB. Have you tried this in action? Also, I believe instead of hard-coding the schema name constant you can move it to the configuration parameter with defaults to schema.sql. Something like @Value("${spring.datasource.schema:schema.sql}")

**Comment by wind86** [comment]
yes, i tried simple action from 'Getting started' with storing temperature and displaying it on the dashboard and it works well. i will move schema constant into the variable like you proposed.

**Comment by damiya14** [comment]
Please help me to configure my thingsboard to use with mysql

**Comment by wind86** [comment]
@damiya14 just apply same changes in the same file one by one and in your database execute following script  dao/src/main/resources/sql/schema-mysql.sql (it will create tables). keep in mind that version has changed since the time i made such intergration and there can be minor issue related to the database schema

**Comment by ji-zhou** [comment]
@wind86 you need change the author of [this commit](https://github.com/thingsboard/thingsboard/pull/904/commits/f682a5d2e23d80136099964a652aa867a3e846fd) from `ubuntu` to you(`wind86`)

**Comment by ji-zhou** [comment]
@wind86 Hi, you need change the author of this commit from ubuntu to you(wind86)

**Comment by ji-zhou** [comment]
@wind86 Hi, you need change the author of [this commit](https://github.com/thingsboard/thingsboard/pull/904/commits/f682a5d2e23d80136099964a652aa867a3e846fd) from `ubuntu` to you(`wind86`).

**Comment by wind86** [comment]
@ji-zhou thank you for your response. Frankly speaking, there were no interest to this PR for almost a year... So, several months ago I have removed virtual machine with this project

**Comment by zhangbiyun** [comment]
@wind86 
I have implemented the function of porting PostgreSQL to MySQL.
In addition to configuration changes, internal SQL/HQL statements also need to be adapted.

If you need customization, please contact: 314218900@qq.com

**Pull request closed without merging**
