### PR TITLE
UI: Fixed assets page 404

### PR DESCRIPTION
**Pull request by blackstar-baba**
If refresh url: http://ip:port/assets, get Whitelabel Error Page

### CODE REVIEW

**Comment by blackstar-baba** [comment]
@vvlladd28 PTAL

**Comment by vvlladd28** [comment]
@blackstar-baba Thx for your contribution!

**Review by vvlladd28 — APPROVED** [review]

**Comment by vvlladd28** [comment]
We've checked your fix; it doesn't fix the issue. We have written a fix that solves this issue #4353

**Comment by blackstar-baba** [comment]
Sorry, my fault, i only test in separation of front-end and backend

**Pull request closed without merging**
