### PR TITLE
UI: Fixed switch control widget, didn't update state after get value in call RPC

### LINKED ISSUE #4311: [Bug] Control Widgets (switch control)
**Describe the bug**
Control widgets - Switch Control (Rectangular)

**Your Server Environment**

  * ThingsBoard Version 3.2.2 (ubuntu 20.04.2 LTS RPI)

**Your Client Environment**

* Browser [chrome,(any browser)]
* Version [89]

* Connectivity
  * MQTT

**To Reproduce**
1. Go to any add Switch control widgets dashboard then feedback switch status(RPC),if switch is on ,feedback statu is dont display "on" some times,but if click edit, the "on" statu is display true.(Round switch dont have this bug)

Capture

### PR DESCRIPTION
**Pull request by vvlladd28**
Fixed #4311

### CODE REVIEW

**Comment by wenzul** [comment]
@vvlladd28 Is it possible to quick fix an existing 3.2.1 PE installation without waiting for a release / having the upgrade overhead?

**Comment by vvlladd28** [comment]
Hi @wenzul, 
You need to wait for the release of TB PE.

**Comment by wenzul** [comment]
Hi @vvlladd28,
thank you for your reply. I thought repacking a fixed JS thingsboard.jar temporarily.
When will you plan a release of PE which fixes this issue?

**Comment by wenzul** [comment]
@vvlladd28 When will be the next release? Thank you.

**Comment by vvlladd28** [comment]
Hi @wenzul, release will planned this month

**Comment by wenzul** [comment]
2 days to go... :)

**Pull request merged**
